# -*- coding: utf-8 -*-
"""Iris_Classifier_ScikitLearn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bZ9de_XN7j5fu3_-_1jlFDsvaPz-Kpp1
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Load your CSV from Drive (update the path if needed)
file_path = '/content/drive/MyDrive/AI_Toolkit_Assignment/Iris_Species_Data/Iris.csv'
df = pd.read_csv(file_path)

# Preview the data
df.head()

# Drop unnecessary 'Id' column if present
df = df.drop('Id', axis=1)

# Encode the species labels
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Species'] = le.fit_transform(df['Species'])

df.head()

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score

# Split features and target
X = df.drop('Species', axis=1)
y = df['Species']

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train the model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')

print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))
plot_tree(model, feature_names=X.columns, class_names=le.classes_, filled=True)
plt.show()